### ISSUE TITLE
TerraClim Data Available through 2018

### ISSUE THREAD

**Issue by pjgoodling** [mikejohnson51/climateR#10]
It looks like the ending data of the TerraClim dataset is hardcoded to be 2017. However data is now available through 2018. It looks like a simple update in getTerraClim will do the trick.

**Comment by mikejohnson51** [comment]
Hi @pjgoodling, this is now fixed, thank you! 

FYI the new terraclim product has a Fill mismatch in the netcdf files. I fixed this by appending #fillmismatch to the end of all terraclim products. It should be stable but I have contacted the server mainters as well.

Thanks again, 

Mike

**Comment by pjgoodling** [comment]
Ok great! Thank you!
