### ISSUE TITLE
Problem using the "get PRISM" command.

### ISSUE THREAD

**Issue by mmfava** [mikejohnson51/climateR#12]
Hello, I need help with an error.

I had a problem with the "getPRISM" command: The moment I request the download of TerraClimate variables using a polygon for Argentina, I end up having the following problem:

### 

AOI = aoi_get(country = "Argentina")
AOI

p = getPRISM(AOI, param = c('tmax', 'tmin', 'prcp'), startDate = "2014-01-01", endDate = "2019-12-30")

### 

**Error in define.grid3(AOI, id) : Requested AOI not in model domain**

###

Can anybody help me, please?

best regards (:
Marília

**Comment by mmfava** [comment]
Oops! The mistake was human here. I found that the getPRISM command does not work for Terra Climate. Sorry!

**Comment by mikejohnson51** [comment]
Awesome :)

Just in case you didn't find the TerraClim function (the documentation here needs some TLC):

```r
library(AOI)
library(climateR)
library(raster)

p = aoi_get(country = "Argentina") %>% 
    getTerraClim(param = c('tmax', 'tmin', 'prcp'), startDate = "2014-01-01")

par(mfrow = c(1,3))
for(i in 1:3){
  plot(p[[i]], main = names(p)[i])
  plot(AOI$geometry, add = T, color = NA)
}
```

Good luck!
