### ISSUE TITLE
'aoiProj' is not an exported object from 'namespace:AOI'

### ISSUE THREAD

**Issue by AntoineCabon** [mikejohnson51/climateR#14]
Hi Mike, 

Thanks for that useful package. 
When running the example code chunk:

```
ts = geocode('Colorado Springs') %>% 
  getLOCA(param = 'tmax', model = 10, startDate = "2030-01-01", endDate = "2040-12-31")
```

I get:
`'aoiProj' is not an exported object from 'namespace:AOI'`

Do you have a fix? 

Thanks 
Antoine

**Comment by mikejohnson51** [comment]
Hi Antoine,

Thank you! This was a test I had not looked at after fixing some issues with AOI.

e573217 should fix this and the following works:

```r
AOI = AOI::geocode('Colorado Springs') %>% 
  getLOCA(param = 'tmax', model = 10, startDate = "2030-01-01", endDate = "2030-01-01") %>% 
  tidyr::pivot_longer(-c(source, lat, lon, date))
```

Beware, the request you have above will take some time (~36525) values. For me it took 51 seconds.

Any feedback on your use case would be welcome!

Thanks again,

Mike

**Comment by AntoineCabon** [comment]
Hi Mike, 

The fix is working for me, thanks!

So, I am actually using your package to compare performance and accuracy with some homemade scripts, which are not perfect to see if I might switch to your code. 

Best, 
Antoine
