### ISSUE TITLE
Error in socketAccept

### ISSUE THREAD

**Issue by rsmiller74** [mikejohnson51/climateR#17]
I get a socket error when I attempt to run getTerrClim.  However same error occurs for examples.  

> tmp<-getTerraClim(AOI=aoi, param=c(var),
+                   startDate=str.date,
+                   endDate=end.date)
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  closing unused connection 125 (<-view-localhost:11875)
3: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  closing unused connection 124 (<-view-localhost:11875)

**Comment by rsmiller74** [comment]
and for example code


> AOI = aoi_get(state = "CA")
> 
> system.time({p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 127 (<-view-localhost:11875)
3: In .Internal(gc(verbose, reset, full)) :
 Rerun with Debug
 Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use Timing stopped at: 0.44 0.06 0.92
>

**Comment by rsmiller74** [comment]
and for example code


> AOI = aoi_get(state = "CA")
> 
> system.time({p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 127 (<-view-localhost:11875)
3: In .Internal(gc(verbose, reset, full)) :
 Rerun with Debug
 Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use Timing stopped at: 0.44 0.06 0.92
>

**Comment by rsmiller74** [comment]
and for example code


> AOI = aoi_get(state = "CA")
> 
> system.time({p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 127 (<-view-localhost:11875)
3: In .Internal(gc(verbose, reset, full)) :
 Rerun with Debug
 Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use Timing stopped at: 0.44 0.06 0.92
>

**Comment by rsmiller74** [comment]
and for example code


> AOI = aoi_get(state = "CA")
> 
> system.time({p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 127 (<-view-localhost:11875)
3: In .Internal(gc(verbose, reset, full)) :
 Rerun with Debug
 Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use Timing stopped at: 0.44 0.06 0.92
>

**Comment by rsmiller74** [comment]
and for example code


> AOI = aoi_get(state = "CA")
> 
> system.time({p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 123 (<-view-localhost:11875)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 127 (<-view-localhost:11875)
3: In .Internal(gc(verbose, reset, full)) :
 Rerun with Debug
 Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use Timing stopped at: 0.44 0.06 0.92
>

**Comment by mikejohnson51** [comment]
Hi @rsmiller74 just making sure your issues here are also closed out :)

``` r
library(AOI)
library(climateR)
library(rasterVis)


AOI = aoi_get(state = "CA")
p = getPRISM(AOI, param = c('tmax','tmin'), startDate = "2018-10-29")

levelplot(stack(p), margin = FALSE, par.settings = BuRdTheme)
```

![](https://i.imgur.com/RpqzEJN.png)

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
