### ISSUE TITLE
Explicit scoping for param_meta in define.param

### ISSUE THREAD

**Issue by mbjoseph** [mikejohnson51/climateR#23]
Hey @mikejohnson51! I'm incorporating climateR into a downstream package, but running into scoping issues. 

When my package calls `getMACA`, the following error is raised: 

```
Error in eval(parse(text = paste0("param_meta$", service))) : 
  object 'param_meta' not found
```

The traceback indicates that this is raised when `climateR::define.param` is called by `climateR::getMACA`:

![image](https://user-images.githubusercontent.com/2664564/104617913-45e26b80-5649-11eb-9995-b51b733bc3ec.png)

**Proposed solution**

Modifying this line to use `climateR::param_meta` instead of `param_meta` solves the issue: https://github.com/mikejohnson51/climateR/blob/master/R/utility_define_param.R#L12

I noticed that you've explicitly specified the scope like this elsewhere where `eval()` is used, e.g., 

https://github.com/mikejohnson51/climateR/blob/fe7414903aa0f0a5ac3149c36c7e3401e92972c9/R/utility_define_config.R#L10

and 

https://github.com/mikejohnson51/climateR/blob/fe7414903aa0f0a5ac3149c36c7e3401e92972c9/R/utility_define_config.R#L34

**Comment by mikejohnson51** [comment]
I think this should be taken care of, thanks again @mbjoseph!

**Comment by mbjoseph** [comment]
cool - thanks @mikejohnson51! :+1:
