### ISSUE TITLE
support for {terra}'s objects

### ISSUE THREAD

**Issue by Nowosad** [mikejohnson51/climateR#44]
Dear @mikejohnson51 -- thanks for the great package.

I am now thinking about adding climateR to the data packages section of the Geocomputation with R book.  As the book uses {terra} for raster data, I have a quick question -- do you have any plans to add terra support for this package?

**Comment by mikejohnson51** [comment]
Hi @Nowosad, 

Wow! What an honor that would be. I have used your book quite a bit and turned many students towards it as well. As for the question, this is perfect timing. I have `terra` capabilities built into a not-pushed climateR branch as well as a few new data sets that support on-going drought, fire, and snow modeling efforts here in the US. I will have that update out by the end of the year.

If there is anything I can do to support the inclusion of `climateR` in Geocomputation with R, please let me know.

Mike

**Comment by Nowosad** [comment]
Great news! Thanks a lot

**Comment by Nowosad** [comment]
Looks great -- I look forward to see it when it is ready

**Comment by mikejohnson51** [comment]
Hi @Nowosad,

While this took much longer then expected, this package has been completely overhauled to be more flexible, robust, and easy to maintain. It now works with any OPeNDAP endpoint (or VRT/TIF file) and provides an internal catalog of over 100,000 data products. To keep with the old style there are a number of resources which have a shortcut function (e.g.`getTerraclim`, `getGridMet`, `getMODIS`) and all data is returned as `SpatRaster` objects. 

If you are still interested in getting an example of this package in your excellent book, I would be eager to help and am now in a position where I can more readily maintain and improve this software. 

Thanks for all you do, 

Mike

**Comment by Nowosad** [comment]
@mikejohnson51 congrats on the progress made and also -- perfect timing. I plan to revise the data chapter in the next few weeks. 

Could you create a pull request that adds climateR to the data packages' table (https://r.geocompx.org/read-write.html#geographic-data-packages).?

**Comment by Nowosad** [comment]
@mikejohnson51 Thanks for adding the terra support!
