### ISSUE TITLE
OPeNDAP / NetCDF data subsetting. 

### ISSUE THREAD

**Issue by dblodgett-usgs** [mikejohnson51/climateR#47]
Something I started working on in intersectr was a basic netcdf subsetting function that was kind of opinionated but also very general to the CF convention. This internal function https://github.com/USGS-R/intersectr/blob/master/R/execute_intersection.R#L303 was a start but I'd like to do more. 

I need to spend a bit more time with it, but this idea might marry up to https://github.com/mikejohnson51/climateR/blob/master/R/utility_fast_download.R well.

**Comment by mikejohnson51** [comment]
See work in opendap.catalog (We've disscussed this - just closing issue). Mostly this is resolved by the fact RNetCDF can read OpenDAP Urls directly without a need to iterate over time.

**Comment by mikejohnson51** [comment]
@dblodgett-usgs please see full package rewrite now on main :)
