### ISSUE TITLE
getPRISM() doesn't return data for specific day

### ISSUE THREAD

**Issue by BaxW** [mikejohnson51/climateR#48]
getPRISM() has been working perfectly for me, but recently I've noticed it returns a weird URL instead of data when I try to get temperature data for the date May 12th 2021.  All points I've tried seem to have this issue. Only data for May 12th 2021 is affected; data for all other dates is returned as expected. For example:

```
library(AOI)
library(climateR)
library(sf)

ptest = st_point(c(-72.42642220, 41.59313330)) %>% 
  st_sfc(crs = 4326) %>% 
  st_sf()

prismTest = getPRISM(ptest, 
                 param = c('tmax', 'tmin'), 
                 startDate = "2021-05-12",
                 endDate = "2021-05-13")

prismTest

```

the object prismTest looks like:

 source      lat       lon       date
1  prism 41.58333 -72.41667 2021-05-12
2  prism 41.58333 -72.41667 2021-05-13
                                                                                                                                   tmax
1 http://convection.meas.ncsu.edu:8080/thredds/dodsC/prism/daily/combo/2021/PRISM_combo_20210512.nc?tmax[0:1:0][200:1:200][1262:1:1262]
2                                                                                                                      18.9360008239746
                                                                                                                                   tmin
1 http://convection.meas.ncsu.edu:8080/thredds/dodsC/prism/daily/combo/2021/PRISM_combo_20210512.nc?tmin[0:1:0][200:1:200][1262:1:1262]
2                                                                                                                      4.01399993896484

As you can see, data for May 13th 2021 is normal, but May 12th is a weird link.

I would appreciate any help figuring out the cause/solution to this. Here's my [session info](https://github.com/mikejohnson51/climateR/files/7873560/baxwSinfo.txt)
Thanks!!!

**Comment by mikejohnson51** [comment]
Hi @BaxW,

Thanks for the note. In climateR, a URL is added as the value in cases where the URL call fails. 

In your case it is because (oddly) the PRISM archive is missing a file for that date:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/30052272/149629656-3c4e09a0-17d8-4dfa-8084-0472e2ba6293.png">

I am searching for a cleaner PRISM archive and hopefully this can help with this issue and I will send them a report of the missing file on Monday. 

Mike

**Comment by mikejohnson51** [comment]
Thanks to John McGuire, over at NC State, the missing file was updated:

```r

library(AOI)
library(climateR)
library(sf)

ptest = st_point(c(-72.42642220, 41.59313330)) %>% 
  st_sfc(crs = 4326) %>% 
  st_sf()

(getPRISM(ptest, 
         param = c('tmax', 'tmin'), 
         startDate = "2021-05-12",
         endDate = "2021-05-13"))


source   lat    lon       date  tmax  tmin
1  prism 41.58 -72.42 2021-05-12 17.45 4.966
2  prism 41.58 -72.42 2021-05-13 18.94 4.014

```

Hope if works for you too,

Mike

**Comment by BaxW** [comment]
Yes, working for me now as well. Thanks!!!
