### ISSUE TITLE
Consider adding NEX-Gridded Daily Meteorology (NEX-GDM) dataset?

### ISSUE THREAD

**Issue by eli-asarian** [mikejohnson51/climateR#51]
NetCDF files: https://data.nas.nasa.gov/geonex/geonexdata/NEX-GDM/. Article describing dataset: Hashimoto et al. 2019 (https://doi.org/10.1002/joc.5995). Excerpt from abstract: "NEX-GDM employs the random forest algorithm for estimation, which allows us to find the best estimate from the spatially continuous data sets. We used the NEX-GDM model to produce historical 1-km daily spatial data for the conterminous United States from 1979 to 2017, including precipitation, minimum temperature, maximum temperature, dew point temperature, wind speed, and solar radiation. In this study, NEX-GDM ingested a total of 30 spatial variables from 13 different data sets, including satellite, reanalysis, radar, and topography data."

I just recently found your climateR package and am looking forward to trying it out (for PRISM, GridMET, and Daymet), looks excellent!

**Comment by mikejohnson51** [comment]
Ah bummer. One bright note is that I am slowly working on generalizing the features of climateR here: https://github.com/mikejohnson51/opendap.catalog

While it won't help with the downloading, it will give you climateR syntax to local files. If you want to transfer this issue over there I would be happy to make it a "main" test case?

Mike

**Comment by mikejohnson51** [comment]
Hi @eli-asarian, This is good enough to remind me :) So check out where we are heading: 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/30052272/150876018-6983f5ac-b9ae-4d53-979e-d539cf13810e.png">

You'll notice "URL" is (poorly named now) but one of the files downloaded from the site you provided. The idea is with a more general OpenDap implementation, and the opinionated climateR inputs, you can get the same results from local resources the package doesn't know about. This is getting close to being ready for use.

Mike

**Comment by mikejohnson51** [comment]
Following up w/ progress:

``` r
library(terra)
#> terra 1.5.12
library(opendap.catalog)
url <- '/Users/mjohnson/Downloads/NEXGDM_srad_2020_v100.nc'
utils:::format.object_size(file.size(url), "auto")
#> [1] "3.7 Gb"

system.time({
  dap = dap_crop(URL = url,
                 AOI = AOI::aoi_get(state = "FL"),
                 startDate = "2020-01-01",
                 endDate = "2020-01-05")  
  
  out = dap_get(dap)
})
#> Warning in getGeoDatum(gm): Didn't find a longitude of prime meridian for datum,
#> assuming 0.
#> Warning in getGeoDatum(gm): Didn't find a semi major axis for datum, assuming
#> WGS84 6378137.0 meters
#> Warning in getGeoDatum(gm): Didn't find an inverse flattening value, assuming
#> WGS84 298.257223563
#> Warning in variable_meta(catolog, verbose = FALSE): raw must include variable
#> column
#> Warning in variable_meta(catolog, verbose = FALSE): trying varname. Chance of
#> failure...
#>    user  system elapsed 
#>   1.093   0.134   1.246

opendap.catalog:::print.dap(dap)
#> vars:   > srad [NA]
#> X:      807 (x)
#> Y:      693 (y)
#> T:      4 (time - 1 days)
#> values: 2,237,004 (vars*X*Y*T)

terra::plot(out$srad)
```

![](https://i.imgur.com/bv7RePn.png)

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eli-asarian** [comment]
Thanks Mike! What functions would I then use to extract a time series of srad for a site (or even better- a collection of sites)?

**Comment by mikejohnson51** [comment]
I dont have that built into a function yet but it could be done like this!

``` r
library(opendap.catalog)
library(terra)
#> terra 1.5.12

# Find 100 random points in Florida
rando_sites <- AOI::aoi_get(state = "FL", county = "all") |> 
  sf::st_sample(100) |> 
  sf::st_as_sf()
#Give them an ID
rando_sites$ID = 1:100

plot(rando_sites['ID'], pch = 16)
```

![](https://i.imgur.com/XyG60t1.png)

``` r
# Use Sites as AOI

nexgdm = dap_crop(URL = '/Users/mjohnson/Downloads/NEXGDM_srad_2020_v100.nc',
                  AOI = rando_sites, 
                  startDate = "2020-01-01", endDate = "2020-01-31") |> 
  dap_get()

# Extract
long = extract(nexgdm$srad, project(vect(rando_sites), terra::crs(nexgdm$srad)))

head(x1)
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'head': object 'x1' not found

# Piviot (if desired)
wide = data.frame(date = as.Date(names(long)[-1]), setNames(data.frame(t(long[,-1])), paste0("site_", long[,1])))

head(wide[,1:5])
#>                  date    site_1    site_2    site_3    site_4
#> 2020-01-02 2020-01-02  9.519531 10.830078 10.759766 10.529297
#> 2020-01-03 2020-01-03  7.743164 10.285156  9.755859  9.753906
#> 2020-01-04 2020-01-04  6.645508  9.632812  7.731445  8.290039
#> 2020-01-05 2020-01-05  9.471680  5.623047  7.507812  7.284180
#> 2020-01-06 2020-01-06 13.290039 13.322266 13.309570 13.300781
#> 2020-01-07 2020-01-07 12.838867 13.512695 12.971680 12.615234

plot(wide$date, wide$site_1, type = "l")
```

![](https://i.imgur.com/zSxfjLb.png)

<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eli-asarian** [comment]
Excellent, thanks so much for your help!

**Comment by mikejohnson51** [comment]
Hi @eli-asarian. This has all been merged into this package now. Hope it helps!
