### ISSUE TITLE
Consider adding National Solar Radiation Database (NSRDB) as a dataset?

### ISSUE THREAD

**Issue by eli-asarian** [mikejohnson51/climateR#52]
Mike, another gridded climate dataset I like but have trouble downloading in large quantities is National Solar Radiation Database (NSRDB). It's the best (highest quality and best resolution) gridded solar radiation dataset in North America. I previously had some R code that would download pixel time series by feeding the API a list of URLs, but NSRDB changed its system and my code doesn't work anymore.  API instructions at https://nsrdb.nrel.gov/data-sets/download-instructions.html. I don't know if it'd be possible to integrate this dataset into climateR (there's no OpenDAP service that I'm aware of), but wanted to mention it just in case.

**Comment by mikejohnson51** [comment]
I have not had luck finding this as a web accessible resource so for now its unlikely to integrate. The change in you code _might_ be that they now require an API key. 

Mike
