### ISSUE TITLE
getLOCA not downloading expected data

### ISSUE THREAD

**Issue by sienna-templeman** [mikejohnson51/climateR#53]
Here's the code I have for obtaining the data, running for 11 different models.
```
models <- c("ACCESS1-0", "ACCESS1-3", "CanESM2", "CESM1-BGC", "CESM1-CAM5", 
            "CMCC-CM", "FGOALS-g2", "GFDL-ESM2G", "MIROC-ESM", 
            "MIROC-ESM-CHEM", "MPI-ESM-LR")

for (imodel in 1:length(models)){
  for (iyear in 1980:2099){
    date_start <- paste0(iyear, "-01-01")
    date_end <- paste0(iyear, "-12-31")
  
    data_raw <- getLOCA(aoi, param = c('prcp'), model = models[imodel], scenario = 'rcp45',
                   startDate = date_start, endDate = date_end)

    data <- stack(data_raw)
    
    writeRaster(data, filename = paste0(models[imodel], "_", iyear, "rcp45__", 'loca.grd'), 
                format = "raster", overwrite = TRUE, options = c("INTERLEAVE=BAND", "COMPRESS=LZW"))
    
    closeAllConnections()
  } #iyear
} #imodel

```
The code runs fine, everything comes out as expected. Now I am going through to analyze the data, going through each file and and taking the sum of each layer (aka day) to get the values. They're coming up much lower than would be expected, though, assuming that the results are in kg/m2/s, which is what the documentation shows with head(param_meta$loca). 

I'm not sure if these are the proper units, as I'm trying to convert to mm/day and am therefore dividing results by 86400, and they don't look like correct values. However, the results generally look like the correct pattern, so I'm not sure if the download worked properly but just is in different units, or if there was an issue with the downloads for all of these files. Apologies if this is a simple question, but I've been going around with it for a few days and haven't found a solution, so just trying to figure out if it's an issue with the data, the units, or the expectation.

**Comment by Rapsodia86** [comment]
Shouldn't you multiply by 86400 instead of dividing?
https://www.researchgate.net/post/How-do-I-convert-ERA-Interim-precipitation-estimates-from-kg-m2-s-to-mm-day

**Comment by mikejohnson51** [comment]
HI @sienna-templeman and thanks for the response @Rapsodia86!

I am currently working on a new climateR backend to solve this (amoung other) issues. 

Looking at the new [`open dap.catalog`](https://mikejohnson51.github.io/opendap.catalog/index.html), it seems the dataset documentation collected by climateR(LOCA) is not representative of all subdatasets (now collected in opendap.catalog):

``` r
models <- c("ACCESS1-0", "ACCESS1-3", "CanESM2", "CESM1-BGC", "CESM1-CAM5", 
            "CMCC-CM", "FGOALS-g2", "GFDL-ESM2G", "MIROC-ESM", 
            "MIROC-ESM-CHEM", "MPI-ESM-LR")

dplyr::filter(opendap.catalog::params, 
              id == 'loca',
              variable == "pr", 
              scenario == "rcp45",
              model %in% models) |> 
  dplyr::select(id, varname, units, model)
#>      id                        varname      units          model
#> 1  loca      pr_ACCESS1-0_r1i1p1_rcp45 kg m-2 s-1      ACCESS1-0
#> 2  loca      pr_ACCESS1-3_r1i1p1_rcp45 kg m-2 s-1      ACCESS1-3
#> 3  loca        pr_CanESM2_r1i1p1_rcp45         mm        CanESM2
#> 4  loca      pr_CESM1-BGC_r1i1p1_rcp45         mm      CESM1-BGC
#> 5  loca     pr_CESM1-CAM5_r1i1p1_rcp45         mm     CESM1-CAM5
#> 6  loca        pr_CMCC-CM_r1i1p1_rcp45         mm        CMCC-CM
#> 7  loca      pr_FGOALS-g2_r1i1p1_rcp45         mm      FGOALS-g2
#> 8  loca     pr_GFDL-ESM2G_r1i1p1_rcp45         mm     GFDL-ESM2G
#> 9  loca      pr_MIROC-ESM_r1i1p1_rcp45         mm      MIROC-ESM
#> 10 loca pr_MIROC-ESM-CHEM_r1i1p1_rcp45         mm MIROC-ESM-CHEM
#> 11 loca     pr_MPI-ESM-LR_r1i1p1_rcp45         mm     MPI-ESM-LR
```

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Specifically, the ACCESS1-XXX models are in kg/m2sec while the other nine are in mm. So as @Rapsodia86 suggested you could multiple the ACCESS1 models by 86400, or, do as you're doing and divide the other 9 by 86400.

I am hoping to get these changes into climateR ASAP, and I am sorry it hung you up.

Mike

**Comment by sienna-templeman** [comment]
Hi @mikejohnson51 - thanks so much for the response, I'm glad it was just a simple issue with the units and not something wonky with the data itself! Much appreciated. And yes, @Rapsodia86 you are correct, it should be multiply rather than divide - been looking at this data all week so prone to typos :) 

Is there a way to download/use the opendap.catalog myself to look at the units etc for other datasets? Since finding this library I plan to use it more for other projects and would love to have another way to check it, but can't find a way to install the opendap.catalog package after looking through the page. Thanks for keeping this library up to date - it is wickedly useful and I'm so glad to have found it!

Cheers,
Sienna

**Comment by sienna-templeman** [comment]
Also, just so you're aware @mikejohnson51 - the units are not consistent in the datasets. For the two ACCESS1 models, the units are in mm up to 2005, then 2006 onward are in kg/m2/s; and the MPI-ESM-LR model is in kg/m2/s up to 2005, then mm 2006 onward. These are the only additional models I needed data for so not sure if there are other models that this is the case with as well, but other than those three periods (for both RCP4.5 and 8.5) everything else is in mm/day. Thanks!

**Comment by mikejohnson51** [comment]
@sienna-templeman Thanks! Fortunately, it does look like this is caught! But a great check. With mikejohnson51/opendap.catalog#7 the units will soon be added to any summary or SpatRast object!

``` r
dplyr::filter(opendap.catalog::params, 
              id == 'loca',
              variable == "pr", 
              grepl('ACCESS1', model)) |> 
  dplyr::select(id, varname, units, model, scenario, duration) |> 
  dplyr::arrange(model)
#>     id                        varname      units     model   scenario
#> 1 loca pr_ACCESS1-0_r1i1p1_historical         mm ACCESS1-0 historical
#> 2 loca      pr_ACCESS1-0_r1i1p1_rcp45 kg m-2 s-1 ACCESS1-0      rcp45
#> 3 loca      pr_ACCESS1-0_r1i1p1_rcp85 kg m-2 s-1 ACCESS1-0      rcp85
#> 4 loca pr_ACCESS1-3_r1i1p1_historical         mm ACCESS1-3 historical
#> 5 loca      pr_ACCESS1-3_r1i1p1_rcp45 kg m-2 s-1 ACCESS1-3      rcp45
#> 6 loca      pr_ACCESS1-3_r1i1p1_rcp85 kg m-2 s-1 ACCESS1-3      rcp85
#>                                  duration
#> 1 1950-01-01 12:00:00/2005-12-31 12:00:00
#> 2 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 3 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 4 1950-01-01 12:00:00/2005-12-31 12:00:00
#> 5 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 6 2006-01-01 12:00:00/2100-12-31 12:00:00
```

<sup>Created on 2022-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Also, sorry for not having in the docs yet:
```r
remotes::install_github('mikejohnson51/opendap.catalog')
```

Should download the package... its very WIP progress now so be warned :)

**Comment by sienna-templeman** [comment]
Perfect - tried that originally but ran into an error (turns out it's because of a firewall with my work laptop so had to switch over and that fixed it). Thanks so much for the help! I have a couple of other questions just for clarification:

Is LOCA hydrology (like evapotranspiration) available in this package, or just the LOCA climatology data?
https://gdo-dcp.ucllnl.org/downscaled_cmip_projections/dcpInterface.html#Projections:%20Subset%20Request
LOCA CMIP5 Hydrology Daily on this site

I noticed that a few models are unavailable for download with the LOCA climate data, for example, "BCC-CSM1" and  "INMCM4". Are these just not able to be downloaded from the package? 
Note - found they were unavailable after they pulled up errors in the code, then looked at model_meta$loca
to check it wasn't just an error on my side.

**Comment by mikejohnson51** [comment]
Hi @sienna-templeman  and @Rapsodia86,

Sorry for the long delay on this. The package has been completely re-written to supply greater flexibility, more datasets, and easier use. This data catalog is now in climateR and I can confirm we are seeing the same thing: 

``` r
library(climateR); library(dplyr)

filter(params, 
              id == 'loca',
              variable == "pr", 
              grepl('ACCESS1', model)) |> 
  select(id, varname, units, model, scenario, duration) |> 
  arrange(model)
#>     id                        varname      units     model   scenario
#> 1 loca pr_ACCESS1-0_r1i1p1_historical         mm ACCESS1-0 historical
#> 2 loca      pr_ACCESS1-0_r1i1p1_rcp45 kg m-2 s-1 ACCESS1-0      rcp45
#> 3 loca      pr_ACCESS1-0_r1i1p1_rcp85 kg m-2 s-1 ACCESS1-0      rcp85
#> 4 loca pr_ACCESS1-3_r1i1p1_historical         mm ACCESS1-3 historical
#> 5 loca      pr_ACCESS1-3_r1i1p1_rcp45 kg m-2 s-1 ACCESS1-3      rcp45
#> 6 loca      pr_ACCESS1-3_r1i1p1_rcp85 kg m-2 s-1 ACCESS1-3      rcp85
#>                                  duration
#> 1 1950-01-01 12:00:00/2005-12-31 12:00:00
#> 2 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 3 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 4 1950-01-01 12:00:00/2005-12-31 12:00:00
#> 5 2006-01-01 12:00:00/2100-12-31 12:00:00
#> 6 2006-01-01 12:00:00/2100-12-31 12:00:00
```

<sup>Created on 2023-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

As for the other questions, I believe we can add the LOCA hydrology. I will open that in a separate issue. 

Unfortunately the models in the catalog (now params) is the complete set available on the server we are hitting. If there are more out there and you can point me to them then I should be able to get them added.

Thanks again to both of you for you help and awesome questions!

Mike
