### ISSUE TITLE
Not able to extract data using PRISM or Daymet

### ISSUE THREAD

**Issue by alherca73** [mikejohnson51/climateR#54]
Hello, I am a brand new user of climateR and while trying to extract time series for PRISM dataset (regardless of what parameter prcp, tmin, tmax): 

Cal<-AOI::aoi_get(state = c("CA"))
Ouput.PRISM<- getPRISM(AOI = Cal, param = c('tmax','tmin'), 
                        startDate = "2011-01-01", endDate = "2015-01-01")

I get the following error:

Spherical geometry (s2) switched off
Spherical geometry (s2) switched on
Error in dim(v) <- round(c(g$rows, g$cols, time)) : 
  dims [product 82667328] do not match the length of object [56544]

An example trying to extract Daymet:
Output.Dayment<- getDaymet(AOI = Cal, param = "prcp", 
                        startDate = "2011-01-01", endDate = "2015-01-01")

I get the error:

Spherical geometry (s2) switched off
Spherical geometry (s2) switched on
syntax error, unexpected $end, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: ^
syntax error, unexpected $end, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: ^
syntax error, unexpected $end, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: ^
syntax error, unexpected $end, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: ^
syntax error, unexpected $end, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: ^
Error in var[[i]] * scale_factor : 
  non-numeric argument to binary operator

Any help will be much appreciated!

Thanks,

Alex

**Comment by mikejohnson51** [comment]
Hi @alherca73 and @kaitlinperkins,

Thanks for the issue and sorry for the delay! The package has been completely re-written to supply greater flexibility, more datasets, and easier use. In this example, both Dayment and PRISM work as expected. One note of caution with PRISM is that the server stores each day of data in a single file. So to extract it, the code will make a request for each per day.

When you make very large requests (e.g. many years) the odds of a server timeout is fairly large. In these cases I would make smaller requests and save the intermediary outputs. If you are able to do this I dont foresee any issues using these resources.

Example from above (with reduced dates for speed):

``` r
library(climateR)
#> Using GDAL version 3.6.0 which was retracted because it cannot write large GPKG files
library(AOI)
library(terra)
#> terra 1.7.9

Cal<-aoi_get(state = c("CA"))
Ouput.PRISM<- getPRISM(AOI = Cal, varname = c('tmax','tmin'),
                       startDate = "2011-01-01", endDate = "2011-02-01")

plot(Ouput.PRISM$tmax$`tmax_2011-01-01`)
```

![](https://i.imgur.com/Oyzo5Cj.png)

``` r

plot(Ouput.PRISM$tmin$`tmin_2011-02-01`)
```

![](https://i.imgur.com/HekpbYq.png)

``` r

Output.Dayment<- getDaymet(AOI = Cal, varname = "prcp",
                          startDate = "2011-01-01", endDate = "2011-02-01")

plot(Output.Dayment$prcp_total[[6]])
```

![](https://i.imgur.com/D4SnCan.png)

<sup>Created on 2023-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I hope the package rewrite proves useful to you if you are still using it and pursuing simular research/data questions. 

Mike
