### ISSUE TITLE
getDaymet error:  "Error in var[[i]] * scale_factor : non-numeric argument to binary operator"

### ISSUE THREAD

**Issue by rsmiller74** [mikejohnson51/climateR#61]
Is this package still being maintained?

When attempting to compile daymet data the "Error in var[[i]] * scale_factor : non-numeric argument to binary operator" is returned.

library(sf)
library(climateR)
packageVersion("climateR")  

library(AOI)
packageVersion("AOI")  

AOI = aoi_get(state = "IL")

p<-getDaymet(AOI=AOI, param="prcp",
             startDate="2020-01-01",
             endDate="2020-12-31")
    

> library(sf)
> library(climateR)
> packageVersion("climateR")  
[1] ‘0.1.0’
> 
> library(AOI)
> packageVersion("AOI")  
[1] ‘0.2.1’
> 
> AOI = aoi_get(state = "IL")
> 
> p<-getDaymet(AOI=AOI, param="prcp",
              startDate="2020-01-01",
              endDate="2020-12-31")
Spherical geometry (s2) switched off
Spherical geometry (s2) switched on
Error in var[[i]] * scale_factor : 
  non-numeric argument to binary operator

**Comment by ERGINCAGATAYCANKAYA** [comment]
I have the same problem. Could you please help us?

**Comment by rsmiller74** [comment]
This is still an issue as of 26 Jan 2023.  See example below.  The error appears to be thrown from 'fast.download' at the end of the getDaymet function.

> aoi.object <- aoi_get(state="VA", county="Fairfax")
> 
> p<-getDaymet(AOI=aoi.object, param="tmax", startDate="2018-01-01", endDate="2018-01-05")
Spherical geometry (s2) switched off
Spherical geometry (s2) switched on
Error in var[[i]] * scale_factor : 
  non-numeric argument to binary operator
>

**Comment by mikejohnson51** [comment]
Hi @rsmiller74  @ERGINCAGATAYCANKAYA ,

Sorry for the long delay on this. The package has been completely re-written to supply greater flexibility, more datasets, and easier use. In this example, all calls to Daymet (and to a larger extent all calls to var[[i]] * scale_factor) have been resolved:

``` r
library(climateR)
#> Using GDAL version 3.6.0 which was retracted because it cannot write large GPKG files
library(AOI)
library(terra)
#> terra 1.7.8

aoi.object <- aoi_get(state="VA", county="Fairfax")

p<-getDaymet(AOI=aoi.object, varname="tmax", startDate="2018-01-01", endDate="2018-01-05")

plot(p$tmax_total)
```

![](https://i.imgur.com/FagOBmG.png)

<sup>Created on 2023-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


I hope the package rewrite proves useful to you if you are still using it and pursuing simular research/data questions.  I am also in a place where I can maintain this software as part of my job and not on the side which will allow much more rapid development and support. 

Thanks again for your patience,

Mike
