### ISSUE TITLE
Is this package being maintained anymore?

### ISSUE THREAD

**Issue by rsmiller74** [mikejohnson51/climateR#63]
Looking at the issues being reported such as getDaymet which was first reported back in July 2021 it appears this package is no longer being actively maintained.  Is this accurate?

https://github.com/mikejohnson51/climateR/issues/41

**Comment by mikejohnson51** [comment]
Hi @rsmiller74, it is! and a major overhaul is coming (hopefully) by the weekend. The new backend for this package is supported here: https://github.com/mikejohnson51/climateR-catalogs. The issues with daymet are corrected in this new package as are some of the more common errors that popped up in the origional version of this package. Sorry for being so slow :) 

Mike

**Comment by mikejohnson51** [comment]
Hi @rsmiller74,

Sorry for the long delay on this. The package has been completely re-written to supply greater flexibility, more datasets, and easier use.  From here on out I can support this as part of my job, and will be able to give it more diligence/updates/ and maintenance. 

Thanks for sticking with me,

Mike
