### ISSUE TITLE
Add utility to animate outputs

### ISSUE THREAD

**Issue by mikejohnson51** [mikejohnson51/climateR#71]
Add `gifski` as a dependency to provide animation tools.

```r
animate = function(data, ...) {

...
}
```

**Comment by mikejohnson51** [comment]
We now have 

```r

AOI = AOI::aoi_get(state = "OR")

g = getGLDAS(AOI = AOI,
         varname='rootmoist_inst',
         model='NOAH025_M.2.1',
         startDate='2006-10-01',
         endDate='2007-09-30')

animation(g$rootmoist_inst, 
          AOI = AOI,
          outfile = "tester.gif")
```
![tester](https://github.com/mikejohnson51/climateR/assets/30052272/a9cef7ea-908c-4213-bcd5-a616af5757ad)

**Comment by mikejohnson51** [comment]
Added vector animation capacity:

```r
getGridMET(AOI,
               varname = "pr",
               startDate = "1991-10-29",
               endDate  = "1991-11-06") %>% 
  execute_zonal(geom = AOI, ID = "fip_code") %>% 
  animation(feild_pattern = "pr_", outfile = "test.gif")
````
![test](https://github.com/mikejohnson51/climateR/assets/30052272/1a4fca97-efff-40c9-9a0c-f3997278e92b)

**Comment by mikejohnson51** [comment]
@anguswg-ucsb would you mind reviewing this changes (in viz.R) and seeing what you'd change/improve?

**Comment by anguswg-ucsb** [comment]
> @anguswg-ucsb would you mind reviewing this changes (in viz.R) and seeing what you'd change/improve?

Yes, I'll take a look and let you know my edits.

**Comment by mikejohnson51** [comment]
Super! If you find/add anything please send it this way as a PR :)
