### ISSUE TITLE
Question and Help: On How to Plot Monthly Data into Yearly Data In Tempreture change Map using getTerra climate 

### ISSUE THREAD

**Issue by Heed725** [mikejohnson51/climateR#94]
Hello @mikejohnson51 and @Rapsodia86 hopefully you guys are doing well and alright, I have three chunk of codes for mean,yearly and monthly for climateR they seemed to work about couple of year ago but now they don't seem to work any more i'll share the codes

![Mean](https://github.com/mikejohnson51/climateR/assets/86722789/c04fa2fe-bb20-4e8d-a96f-bdc59ed970dd)
![Monthly](https://github.com/mikejohnson51/climateR/assets/86722789/91333369-79d7-42bf-92e3-0abb83db91d2)
![yearly](https://github.com/mikejohnson51/climateR/assets/86722789/d5604961-4821-4ef6-b8f8-e1c78f597510)

But mostly i'm getting masking error ,could you help me out on updating or figuring out  so it can work again

**Comment by mikejohnson51** [comment]
``` r
library(climateR)
library(terra)
library(tidyterra)
library(ggplot2)

SAU = AOI::aoi_get(country = "SAU")

test_data = getTerraClim(
  AOI = SAU,
  varname = "tmax",
  startDate = "2011-01-01",
  endDate   = "2012-12-01",
  dryrun = F
)

data = tapp(test_data[[1]],
            rep(1:(nlyr(test_data[[1]]) / 12), 12),
            mean) |>
  mask(project(vect(SAU), crs(test_data[[1]])))

ggplot() +
  geom_spatraster(data = data) +
  geom_spatvector(data = SAU, fill = NA, lwd = 1) +
  facet_wrap( ~ lyr) +
  scale_fill_whitebox_c(
    palette  = "muted",
    n.breaks = 12,
    guide    = guide_legend(reverse = TRUE)
  ) +
  theme_minimal()
```

![](https://i.imgur.com/87a6q7R.png)

<sup>Created on 2024-03-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Heed725** [comment]
Okay thank you much very this is cool visual but I have few 3 questions. 

1.The above is cool but instead of x1 ,x2, x3 how can I label like January, February , march etc.?
2.The above is for monthly basis which is cool how will code appear in yearly basis? like it to appear two maps of only 2011 and 2012.
3.How does code appear like in one mean average temperature ? like one big visual showing mean Temperature of 2011 and 2012 ?

Thats all I think but thank you very much for this one

**Comment by mikejohnson51** [comment]
Two small adjustments should get you that!
``` r
library(climateR)
library(terra)
library(tidyterra)
library(ggplot2)

SAU = AOI::aoi_get(country = "SAU")

test_data = getTerraClim(
  AOI = SAU,
  varname = "tmax",
  startDate = "2011-01-01",
  endDate   = "2012-12-01"
)

data = tapp(test_data[[1]],
            rep(1:(nlyr(test_data[[1]]) / 12), 12),
            mean) |>
  mask(project(vect(SAU), crs(test_data[[1]])))

names(data) = c("Y2011", "Y2012")

ggplot() +
  geom_spatraster(data = data) +
  geom_spatvector(data = SAU, fill = NA, lwd = 1) +
  facet_wrap( ~ lyr) +
  scale_fill_whitebox_c(
    palette  = "muted",
    n.breaks = 12,
    guide    = guide_legend(reverse = TRUE)
  ) +
  theme_minimal()
```

![](https://i.imgur.com/nzW791g.png)

<sup>Created on 2024-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mikejohnson51** [comment]
Maybe something like: 

```r

data = mask(mean(test_data[[1]]), project(vect(SAU), crs(test_data[[1]])))

ggplot() +
  geom_spatraster(data = data) +
  geom_spatvector(data = SAU, fill = NA, lwd = 1) +
  scale_fill_whitebox_c(
    palette  = "muted",
    n.breaks = 12,
    guide    = guide_legend(reverse = TRUE)
  ) +
  labs(title = "Mean Daily Max Temp") + 
  theme_minimal()


```

**Comment by Heed725** [comment]
@mikejohnson51 Hey I think for me I'm done ,Thank you so so much for the great help....I'm really grateful for that.....I guess I'll see you when you update climateR again :).

**Comment by Heed725** [comment]
I'm Back again with one last tiny question ? I altered the code a bit  let me show you 
```r
library(climateR)
library(terra)
library(tidyterra)
library(ggplot2)
library(colorspace)

SAU = AOI::aoi_get(country = "SAU")

test_data = getTerraClim(
  AOI = SAU,
  varname = "tmax",
  startDate = "2011-01-01",
  endDate   = "2012-12-01"
)

data = tapp(test_data[[1]],
            rep(1:(nlyr(test_data[[1]]) / 12), 12),
            mean) |>
  mask(project(vect(SAU), crs(test_data[[1]])))

names(data) = c("2011", "2012")

ggplot() +
  geom_spatraster(data = data) +
  geom_spatvector(data = SAU, fill = NA, lwd = 1) + # Set color to "black"
  facet_wrap( ~ lyr) +
  scale_fill_continuous_sequential(palette = "YlOrRd") +
  labs(title = "Yearly temperature of Saudi Arabia of the years 2011 and 2012",
       fill = "Temperature (°C)") + # Add title
  theme_minimal() 
```
It gives me this output but how do I remove grey color surrounding The Area of Interest(Saudi Arabia)

![Saudii](https://github.com/mikejohnson51/climateR/assets/86722789/c42155d7-2fdd-4f64-a7b5-21f48384b1d0)

**Comment by Rapsodia86** [comment]
Maybe this will help:
https://dieghernan.github.io/tidyterra/articles/faqs.html#nas-remove

**Comment by Heed725** [comment]
Thank you so so much 
![Saudi New](https://github.com/mikejohnson51/climateR/assets/86722789/863e0d93-136a-4ba7-a24d-c3813828a53b)

**Comment by mikejohnson51** [comment]
Closing for now. Thanks All!
